### PR TITLE
Commit generated pfvar

### PR DESCRIPTION
**Pull request by faern**
Generating the the bindings with bindgen on build had the problem that it was dependent on finding the macOS SDK path. Thus the library could only be build on a machine with xcode installed. This is unfortunate. And it blocks docs.rs from building the docs as well: https://docs.rs/pfctl/0.1.0/pfctl/

bindgen recommends building bindings on the fly with a buildscript, like we do before this PR: https://rust-lang-nursery.github.io/rust-bindgen/tutorial-1.html, but that does not work very well for us. Also, these bindings are quite unlikely to change. Or at least the C source header is. The generated code can change because of changes to bindgen or rustfmt of course.

What I did was to change the code in `build.rs` into a bash script calling the bindgen binary instead to generate the same binding result, but commit that resulting binding as well. So if we have `pfvar.h` and `generate_bindings.sh` in the repo it becomes very easy to re-generate the bindings on bindgen updates or similar. But for ordinary people who just want to build the library they are now not required to have xcode and they also don't have to build bindgen at all.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/58)

### CODE REVIEW

**Comment by faern** [comment]
@pronebird Please verify that you get the same results if you try to generate the binding with this new script. Will be interesting to see if it's stable over macOS version etc. Make sure to have the latest version of bindgen and rustfmt installed:
`cargo +nightly install -f bindgen rustfmt-nightly`

**Comment by pronebird** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[generate_bindings.sh, line 3 at r1](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58#-L29TddlCHbXh1BZpbST:-L29TddlCHbXh1BZpbSU:b-5sa3rl) ([raw file](https://github.com/mullvad/pfctl-rs/blob/ad39818fbc34b07ab1d77c160134261b20741434/generate_bindings.sh#L3)):*
> ```Shell
> #!/usr/bin/env bash
> 
> SDK_PATH="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/"
> ```

This will be breaking on each release of the operating system. Why not to run xcodebuild as we used to to get this path?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58)*

**Comment by pronebird** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58)*

**Comment by pronebird** [comment]
I'll test it and report back.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58#-:-L29USympiQv_lKXoFBP:b7xiht4)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[generate_bindings.sh, line 3 at r1](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58#-L29TddlCHbXh1BZpbST:-L2Al6seVozCRhh3k5Bb:b-wzlao2) ([raw file](https://github.com/mullvad/pfctl-rs/blob/ad39818fbc34b07ab1d77c160134261b20741434/generate_bindings.sh#L3)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

This will be breaking on each release of the operating system. Why not to run xcodebuild as we used to to get this path?
</blockquote></details>

I thought I already fixed that... Must have just tested it locally without commiting. Yes I'll fix that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58)*

**Comment by pronebird** [comment]
I get the same bindings build, except the preamble but that's irrelevant :)

```
-// automatically generated by rust-bindgen
+/* automatically generated by rust-bindgen */
```

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58#-:-L2Kk5AptYVOWlS5I0R8:b7rpkxs)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[generate_bindings.sh, line 3 at r1](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58#-L2Kmz3XgD9XcOK3-9ga:-L2Kmz3XgD9XcOK3-9gb:b6agim1) ([raw file](https://github.com/mullvad/pfctl-rs/blob/ad39818fbc34b07ab1d77c160134261b20741434/generate_bindings.sh#L3)):*
> ```Shell
> #!/usr/bin/env bash
> 
> SDK_PATH="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/"
> ```

We could probably use `/System/Library/Frameworks/Kernel.framework/Headers/` which should exist if CLI tools are installed. Xcode offers to install them and that makes total sense for command line builds.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[generate_bindings.sh, line 3 at r1](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58#-L2Kmz3XgD9XcOK3-9ga:-L2KoA1I_K0yVQbKIr2j:b-mssk5e) ([raw file](https://github.com/mullvad/pfctl-rs/blob/ad39818fbc34b07ab1d77c160134261b20741434/generate_bindings.sh#L3)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

We could probably use `/System/Library/Frameworks/Kernel.framework/Headers/` which should exist if CLI tools are installed. Xcode offers to install them and that makes total sense for command line builds.
</blockquote></details>

Oh yes, and CLI tools are ~100M only and can be downloaded from `https://developer.apple.com/download/more/`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58)*

**Comment by pronebird** [comment]
As discussed on Slack, I vote for this PR.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58#-:-L2KoaXrxIyAUoowa0M0:bzb6slv)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Cargo.toml, line 33 at r1](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58#-L2KpCZipEyD7ueliOS-:-L2KpCZipEyD7ueliOS0:b-mwgyaf) ([raw file](https://github.com/mullvad/pfctl-rs/blob/c0027439710fdc627f407199abad3f0087aaa564/Cargo.toml#L33)):*
> ```TOML
> 
> [build-dependencies]
> bindgen = "0.32"
> ```

if you entirely remove the bindgen,  the one would have to install it separately in order to run the shell script, am I right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58)*

**Comment by faern** [comment]
Run `./format.sh` and the `/* ... */` comment will be formatted correctly again :)

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58#-L2KtejaflrBorklt8SD:-L2KtejbuMDJml3QoVX1:b-51djiq) (no related file):*
When pondering about how to solve this issue I have been thinking about whether or not a crate that is platform dependent should fail on invalid platforms or build empty. I created an issue for this in the Rust API guidelines repo, so maybe there can be some official guideline to use for these situations in the future: https://github.com/rust-lang-nursery/api-guidelines/issues/152

---

*[Cargo.toml, line 33 at r1](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58#-L2KpCZipEyD7ueliOS-:-L2KtNRU_YCn9kZoRxzO:bjzq5oy) ([raw file](https://github.com/mullvad/pfctl-rs/blob/c0027439710fdc627f407199abad3f0087aaa564/Cargo.toml#L33)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

if you entirely remove the bindgen,  the one would have to install it separately in order to run the shell script, am I right?
</blockquote></details>

Yes. You need to separately install it no matter what. Just depending on it in this toml will not make the CLI version available to you

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58#-:-L2KtFygeG6mueV-X-56:b-faklsr)*

**Comment by pronebird** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58#-L2KtejaflrBorklt8SD:-L2KuTkwGng5vu0sbnZp:b-k0x75m) (no related file):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

When pondering about how to solve this issue I have been thinking about whether or not a crate that is platform dependent should fail on invalid platforms or build empty. I created an issue for this in the Rust API guidelines repo, so maybe there can be some official guideline to use for these situations in the future: https://github.com/rust-lang-nursery/api-guidelines/issues/152
</blockquote></details>

Thought about the same thing. I think it's fine if project compiles to empty shell on unsupported platforms. It's fail safe even if somebody included the crate by mistake or maybe somebody included all crates at once and then used `cfg` to compile and import relevant parts for corresponding OSes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58)*

**Comment by faern** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[generate_bindings.sh, line 3 at r1](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58#-L2Kmz3XgD9XcOK3-9ga:-L2KvJKGiKuZ4OtCdj6K:b65m5fh) ([raw file](https://github.com/mullvad/pfctl-rs/blob/ad39818fbc34b07ab1d77c160134261b20741434/generate_bindings.sh#L3)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Oh yes, and CLI tools are ~100M only and can be downloaded from `https://developer.apple.com/download/more/`
</blockquote></details>

So you think we should use the global paths instead of using `xcodebuild` in this script? That would work I guess. But if one needs the CLI tools anyway to have the headers installed at `/System/...` then I don't see what the advantage is really?

With the `xcodebuild` version we get the SDK version in the path (`/.../MacOSX10.13.sdk/`), and now I added so that is printed. Should make it easier to spot problems on re-generation of these headers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58)*

**Comment by pronebird** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58#-L2KtejaflrBorklt8SD:-L2KwFjrzuHNJvSUQos6:bf1a1v) (no related file):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Thought about the same thing. I think it's fine if project compiles to empty shell on unsupported platforms. It's fail safe even if somebody included the crate by mistake or maybe somebody included all crates at once and then used `cfg` to compile and import relevant parts for corresponding OSes.
</blockquote></details>

I meant: included the crate by mistake on unsupported platform.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58)*

**Comment by pronebird** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[generate_bindings.sh, line 3 at r1](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58#-L2Kmz3XgD9XcOK3-9ga:-L2KwTjK1qU2HZ2kyufd:b-c3w2x6) ([raw file](https://github.com/mullvad/pfctl-rs/blob/ad39818fbc34b07ab1d77c160134261b20741434/generate_bindings.sh#L3)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

So you think we should use the global paths instead of using `xcodebuild` in this script? That would work I guess. But if one needs the CLI tools anyway to have the headers installed at `/System/...` then I don't see what the advantage is really?

With the `xcodebuild` version we get the SDK version in the path (`/.../MacOSX10.13.sdk/`), and now I added so that is printed. Should make it easier to spot problems on re-generation of these headers.
</blockquote></details>

I had an impression that `xcodebuild` doesn't come with the CLI tools. I may be wrong though. Just use `xcodebuild`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58)*

**Comment by pronebird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58#-L2KtejaflrBorklt8SD:-L2KwVMzNh_DEThrrytR:b9jnl8z) (no related file):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

I meant: included the crate by mistake on unsupported platform.
</blockquote></details>

I don't think it's a priority at all to help people who "include by mistake". To do so is an error and it's more helpful to tell them so rather than be silent. Rust usually don't encourage the i'll-try-to-automagically-correct-for-this-user-error approach that for example Python has a lot of.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58#-L2KtejaflrBorklt8SD:-L2L3f6wZC8MpUlAH1lp:b-cwv6g4) (no related file):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I don't think it's a priority at all to help people who "include by mistake". To do so is an error and it's more helpful to tell them so rather than be silent. Rust usually don't encourage the i'll-try-to-automagically-correct-for-this-user-error approach that for example Python has a lot of.
</blockquote></details>

Anyway. That is not really relevant here and now anyway. Since if we go with this solution we have here it should hopefully compile on all platforms anyway. No `xcodebuild` or other things used at compile time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/58)*

**Pull request merged**
