### PR TITLE
refactor: remove unnecessary `u32` casts

### PR DESCRIPTION
**Pull request by hamirmahal**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/91)

### CODE REVIEW

**Review by hamirmahal — COMMENTED** [review]
.

**Comment by faern** [comment]
Thanks for the PR. We'll wait until #93 and #89 are merged. That way we'll know if the updated bindings changes anything and if the CI catch anything weird.

**Comment by faern** [comment]
The new bindings have been merged. So if you want to you can rebase this on top of `main` and try it out and see if it works locally for you and if the automatic tests pass.

**Comment by hamirmahal** [comment]
Okay, I'll try it out.

**Comment by faern** [comment]
All the CI stuff has been merged! Feel free to rebase again and I'll merge if it passes.

**Comment by hamirmahal** [comment]
Nice! I went ahead and updated this branch, although it looks like this PR needs maintainer approval to run the CI checks.

**Comment by faern** [comment]
I was a bit afraid it would turn out like this with the new bindings. The new bindings generate actual Rust enums for the anonymous C enums, not just ints. This has the benefit that related constants are grouped and a bit stricter typed. But the downside is that they must be cast to be used as integers again.

I don't think we can merge this?

**Comment by hamirmahal** [comment]
Ah, I understand. I'll go ahead and close this.

**Pull request closed without merging**
