### PR TITLE
Upgrade various

### PR DESCRIPTION
**Pull request by faern**
Upgrading lazy_static since it finally hit 1.0
Upgrading bindgen cause it's nice to have the latest.
Upgrading rustfmt since we more or less need the latest for it to even build.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/55)

### CODE REVIEW

**Comment by faern** [comment]
@pronebird Could you please check out this branch and verify that the tests work locally for you? Just want to be extra sure the upgrades does not break anything.

**Comment by faern** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[rustfmt.toml, line 11 at r2](https://reviewable.io:443/reviews/mullvad/pfctl-rs/55#-L0PMruWXOR0eFM3wdWZ:-L0PMruXZgEU_g5vlJm3:b-9jwju0) ([raw file](https://github.com/mullvad/pfctl-rs/blob/d3d5f200d98351992aef3aaf686ac57f96a26899/rustfmt.toml#L11)):*
> ```TOML
> # Heavily subjective style choices
> comment_width = 100
> blank_lines_upper_bound = 2
> ```

rustfmt now makes sure you don't have too many empty lines between blocks. By default it allows only one blank line between blocks. Since we quite often use 2 empty lines to separate a bit unrelated code, such as this:
```rust
struct Foo;

impl Foo {
}


struct Bar;

impl Bar {
}
```
I felt it was justified to increase this limit in order to be able to keep using a bit more separation between unrelated blocks. Do you agree. As you can see it still removes some empty lines in places where we used >2 empty lines between blocks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/55)*

**Comment by faern** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[rustfmt.toml, line 11 at r2](https://reviewable.io:443/reviews/mullvad/pfctl-rs/55#-L0PMruWXOR0eFM3wdWZ:-L0PNiC6tCq0bT6C2fWj:bqaew8j) ([raw file](https://github.com/mullvad/pfctl-rs/blob/d3d5f200d98351992aef3aaf686ac57f96a26899/rustfmt.toml#L11)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

rustfmt now makes sure you don't have too many empty lines between blocks. By default it allows only one blank line between blocks. Since we quite often use 2 empty lines to separate a bit unrelated code, such as this:
```rust
struct Foo;

impl Foo {
}


struct Bar;

impl Bar {
}
```
I felt it was justified to increase this limit in order to be able to keep using a bit more separation between unrelated blocks. Do you agree. As you can see it still removes some empty lines in places where we used >2 empty lines between blocks.
</blockquote></details>

"Do you agree?" was supposed to be a question. I forgot the question mark.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/55)*

**Comment by pronebird** [comment]
I only get few warnings during compilation

```
warning: variable does not need to be mutable
  --> src/rule/mod.rs:54:45
   |
54 | #[derive(Debug, Clone, PartialEq, Eq, Hash, Builder)]
   |                                             ^^^^^^^ help: remove this `mut`
   |
   = note: #[warn(unused_mut)] on by default

warning: variable does not need to be mutable
  --> src/rule/mod.rs:54:45
   |
54 | #[derive(Debug, Clone, PartialEq, Eq, Hash, Builder)]
   |                                             ^^^^^^^ help: remove this `mut`

warning: variable does not need to be mutable
   --> src/rule/mod.rs:136:45
    |
136 | #[derive(Debug, Clone, PartialEq, Eq, Hash, Builder)]
    |                                             ^^^^^^^ help: remove this `mut`

    Finished dev [unoptimized + debuginfo] target(s) in 20.13 secs
```

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/55#-:-L0d3yKtsnF19E76s2Zp:b-5b5cjx)*

**Comment by faern** [comment]
Run `cargo update`, there's a new release of `derive_builder` fixing that problem :)

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/55#-:-L0d4EyzP7eJyEcWrQYZ:b-8f7953)*

**Comment by pronebird** [comment]
Doing that right now

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/55#-:-L0d5T5jV6mxGPZPtZgR:b-v15b09)*

**Comment by pronebird** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[rustfmt.toml, line 11 at r2](https://reviewable.io:443/reviews/mullvad/pfctl-rs/55#-L0PMruWXOR0eFM3wdWZ:-L0d7k3dRbloUo_iTb76:bx0c8j8) ([raw file](https://github.com/mullvad/pfctl-rs/blob/d3d5f200d98351992aef3aaf686ac57f96a26899/rustfmt.toml#L11)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

"Do you agree?" was supposed to be a question. I forgot the question mark.
</blockquote></details>

I noticed this change. Yes that's totally reasonable, I don't like too many blank lines around as they turn the code into art, stricter code style is better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/55)*

**Comment by pronebird** [comment]
Reviewed 2 of 2 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/55)*

**Comment by pronebird** [comment]
`cargo update` worked out!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/55#-:-L0d85WtGg8yluT50oGK:b-1okqed)*

**Comment by pronebird** [comment]
All tests pass for me!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/55#-:-L0d8C4YKY8VOFd69NZH:b-tan0ca)*

**Pull request merged**
