### PR TITLE
Rework main into examples

### PR DESCRIPTION
**Pull request by faern**
`main.rs` just functioned as a sandbox for trying out features. Almost all of the code in there was good to showcase how to use the library, but the "CLI" part of this crate was kind of useless. So I transformed the code in `main.rs` into a number of simple examples that can be executed with `cargo run --example <name>`. I did not keep everything in `main.rs`, but everything I felt was worth showcasing.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/54)

### CODE REVIEW

**Comment by pronebird** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/add_rules.rs, line 71 at r1](https://reviewable.io:443/reviews/mullvad/pfctl-rs/54#-Kzhl6sRjihizm5_5WqB:-Kzhl6sRjihizm5_5WqC:b-6qg4vm) ([raw file](https://github.com/mullvad/pfctl-rs/blob/fbce288fde26e5bd06fa0822efe14da5423d3a48/examples/add_rules.rs#L71)):*
> ```Rust
>     println!("Added a bunch of rules to the {} anchor.", ANCHOR_NAME);
>     println!("Run this command to remove them:");
>     println!("sudo pfctl -a {} -f /dev/null", ANCHOR_NAME);
> ```

Or `sudo pfctl -a {} -F all`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/54)*

**Comment by pronebird** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/enable.rs, line 22 at r1](https://reviewable.io:443/reviews/mullvad/pfctl-rs/54#-KzhlG1SB0OlhYzon3Y1:-KzhlG1SB0OlhYzon3Y2:b-xgntwq) ([raw file](https://github.com/mullvad/pfctl-rs/blob/fbce288fde26e5bd06fa0822efe14da5423d3a48/examples/enable.rs#L22)):*
> ```Rust
>     let mut pf = PfCtl::new().chain_err(|| "Unable to connect to PF")?;
> 
>     // Try to enable the firewall. Exuivalent to the CLI command "pfctl -e".
> ```

~Exuivalent~ Equivalent

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/54)*

**Comment by pronebird** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/transaction.rs, line 61 at r1](https://reviewable.io:443/reviews/mullvad/pfctl-rs/54#-KzhlNtySonP6JN9LF-G:-KzhlNtySonP6JN9LF-H:bd5bkdn) ([raw file](https://github.com/mullvad/pfctl-rs/blob/fbce288fde26e5bd06fa0822efe14da5423d3a48/examples/transaction.rs#L61)):*
> ```Rust
>     println!("Added a bunch of rules to the {} anchor.", ANCHOR_NAME);
>     println!("Run this command to remove them:");
>     println!("sudo pfctl -a {} -f /dev/null", ANCHOR_NAME);
> ```

`-F all` can be used to clear all rules

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/54)*

**Comment by pronebird** [comment]
Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/rule/mod.rs, line 97 at r1](https://reviewable.io:443/reviews/mullvad/pfctl-rs/54#-KzhlVbvZD7WhUTL6Z_4:-KzhlVbvZD7WhUTL6Z_5:b-javgl2) ([raw file](https://github.com/mullvad/pfctl-rs/blob/fbce288fde26e5bd06fa0822efe14da5423d3a48/src/rule/mod.rs#L97)):*
> ```Rust
>         match (self.keep_state, self.proto) {
>             (StatePolicy::None, _)
>             | (StatePolicy::Keep, _)
> ```

Is it new rustfmt's thing now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/54)*

**Comment by pronebird** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/54)*

**Comment by pronebird** [comment]
Absolutely loving it!

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/54#-:-KzhlboASLX6e8bj6KZj:b-t5rosk)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[examples/add_rules.rs, line 71 at r1](https://reviewable.io:443/reviews/mullvad/pfctl-rs/54#-Kzhl6sRjihizm5_5WqB:-Kzhomksp7um-fncFARg:b7dal9j) ([raw file](https://github.com/mullvad/pfctl-rs/blob/fbce288fde26e5bd06fa0822efe14da5423d3a48/examples/add_rules.rs#L71)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Or `sudo pfctl -a {} -F all`
</blockquote></details>

Awesome. Did not know about this. Fixed!

---

*[examples/enable.rs, line 22 at r1](https://reviewable.io:443/reviews/mullvad/pfctl-rs/54#-KzhlG1SB0OlhYzon3Y1:-Kzhp5_2fC9efNcyMXUW:b-896fix) ([raw file](https://github.com/mullvad/pfctl-rs/blob/fbce288fde26e5bd06fa0822efe14da5423d3a48/examples/enable.rs#L22)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

~Exuivalent~ Equivalent
</blockquote></details>

Done.

---

*[examples/transaction.rs, line 61 at r1](https://reviewable.io:443/reviews/mullvad/pfctl-rs/54#-KzhlNtySonP6JN9LF-G:-Kzhp6wdczGnD2Pm8Qqu:b-896fix) ([raw file](https://github.com/mullvad/pfctl-rs/blob/fbce288fde26e5bd06fa0822efe14da5423d3a48/examples/transaction.rs#L61)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

`-F all` can be used to clear all rules
</blockquote></details>

Done.

---

*[src/rule/mod.rs, line 97 at r1](https://reviewable.io:443/reviews/mullvad/pfctl-rs/54#-KzhlVbvZD7WhUTL6Z_4:-Kzhp8ma4uiOxy1zRxbn:bmvg0z0) ([raw file](https://github.com/mullvad/pfctl-rs/blob/fbce288fde26e5bd06fa0822efe14da5423d3a48/src/rule/mod.rs#L97)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Is it new rustfmt's thing now?
</blockquote></details>

Yup. When upgrading to `0.2.16` it did this change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/54)*

**Comment by pronebird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/54#-:-KzhuG8tBImcw7bZ150a:bnfp4nl)*

**Pull request merged**
