### PR TITLE
Prepare release

### PR DESCRIPTION
**Pull request by faern**
Realized we didn't even have the repository url in the metadata. Added that and improved the categories/keywords a bit.

Also clarified some things in the readme and added references to the example code.

I'm planning on publishing `0.1.0` when this is merged.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/57)

### CODE REVIEW

**Comment by faern** [comment]
Also re-exported the `ipnetwork` types. So it becomes possible to use them without also depending on that crate. It's good API design style. Otherwise a user of `pfctl-rs` must always make sure to depend on the exact same version of `ipnetwork` as `pfctl-rs`. With the re-export that is solved automatically and they can just use `pfctl::IpNetwork` directly.

**Comment by pronebird** [comment]
Reviewed 1 of 4 files at r1, 1 of 13 files at r2.
Review status: 2 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/57)*

**Comment by pronebird** [comment]
Reviewed 2 of 4 files at r1, 12 of 13 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/pfctl_test/Cargo.toml, line 7 at r2](https://reviewable.io:443/reviews/mullvad/pfctl-rs/57#-L0nUFnhASUuyrSMFcLz:-L0nUFnhASUuyrSMFcM-:brd06mz) ([raw file](https://github.com/mullvad/pfctl-rs/blob/a63376d7ea255a41a04d4aa73f3ae54485929d23/tests/pfctl_test/Cargo.toml#L7)):*
> ```TOML
> 
> [dependencies]
> error-chain = "0.11"
> ```

Are you use none of these packages are needed to compile tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/57)*

**Comment by faern** [comment]
I had to change `pfctl_test` to a module. Since I can't publish a crate that depends on a non-published crate and we probably don't want to publish `pfctl_test`. But this should also work fine I hope.

---

Review status: 13 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/pfctl_test/Cargo.toml, line 7 at r2](https://reviewable.io:443/reviews/mullvad/pfctl-rs/57#-L0nUFnhASUuyrSMFcLz:-L0nWhHtwADBQKXFVrVE:bsa0c5f) ([raw file](https://github.com/mullvad/pfctl-rs/blob/a63376d7ea255a41a04d4aa73f3ae54485929d23/tests/pfctl_test/Cargo.toml#L7)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Are you use none of these packages are needed to compile tests?
</blockquote></details>

`scopeguard` was needed. Missed that. Added to `[dev-dependencies]` of the parent crate now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/57#-:-L0nWmqleAvi_VmbnVkM:ba3eakh)*

**Comment by pronebird** [comment]
Reviewed 1 of 13 files at r2, 8 of 8 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/57)*

**Comment by pronebird** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/57#-:-L0nbhEyEWOd-FNcKuU7:bnfp4nl)*

**Comment by pronebird** [comment]
Looks good to me!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/57#-:-L0nbkEjVev4Ue-AFphs:b9j9n3q)*

**Comment by pronebird** [comment]
Reviewed 8 of 9 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/pfctl-rs/57)*

**Pull request merged**
