### PR TITLE
Update pfvar bindings

### PR DESCRIPTION
**Pull request by faern**
Uses bindgen 0.69.4 and newer pfvar.h from https://raw.githubusercontent.com/apple-oss-distributions/xnu/1031c584a5e37aff177559b9f69dbd3c8c3fd30a/bsd/net/pfvar.h

This removes `pfvar.h` from this repo and instead instruct the developer to get their own copy from XNU.

This also changes bindings to generate Rust style enums even for C enums without any name. They still have ugly generated names, but it's way easier to see which constants belong together. Everywhere where we use these constants we cast them using `as u8` anyway, so the Rust code "just works".

This supersedes #87. Sorry @pronebird I felt it was easier to just do this than to instruct you how I wanted it.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/93)

### CODE REVIEW

**Comment by faern** [comment]
Sure. I can do that. Did not feel there was much to cherry pick. Got different bindings than you

**Comment by faern** [comment]
@pronebird There is nothing I can cherry-pick. Because all your relevant changes are squashed with the changes I don't want. The only thing you do in your branch that I want is to update `--whitelist` to `--allowlist` and change `v4` to `_v4addr`. The rest is done differently in this PR.

**Comment by faern** [comment]
I both created and merged #90 before I even saw there was an open PR doing the same thing. I like PRs more isolated to doing one thing.

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/93#-:-Nz2JOou7sEhOExefGNM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
