### PR TITLE
Fix a few clippy lints. Small code improvements

### PR DESCRIPTION
**Pull request by faern**
I'm preparing to make a release. Just ran `clippy` and fixed some low hanging stuff first.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/78)

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/78)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[src/utils.rs, line 17 at r1](https://reviewable.io/reviews/mullvad/pfctl-rs/78#-MUDITG-412TRWoHOfay:-MUDITG-412TRWoHOfaz:b-4bzo9r) ([raw file](https://github.com/mullvad/pfctl-rs/blob/351b0ed6a27ca7bdae4c223b1e69096aff197a0b/src/utils.rs#L17)):*
> ```XML
> 
> /// The path to the PF device file this library will use to communicate with PF.
> const PF_DEV_PATH: &'static str = "/dev/pf";
> ```

is it implied now since we use `const`?

**Review by pronebird — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/78#-:-MUDIaZ3E1ljcmJLliv9:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/78)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/78)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[src/utils.rs, line 17 at r1](https://reviewable.io/reviews/mullvad/pfctl-rs/78#-MUDITG-412TRWoHOfay:-MUDJECl6MiBCDBtGcNZ:b-1t252h) ([raw file](https://github.com/mullvad/pfctl-rs/blob/351b0ed6a27ca7bdae4c223b1e69096aff197a0b/src/utils.rs#L17)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

is it implied now since we use `const`?
</blockquote></details>

Exactly. All constants/statics by definition have lifetime `'static`. Early on you had to specify this. But some Rust version pretty long ago removed that requirement and now `clippy` even lints against specifying the lifetime since there is only one valid lifetime anyway.

**Review by pronebird — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/78)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
