### PR TITLE
Add github actions CI and remove travis CI

### PR DESCRIPTION
**Pull request by faern**
The CI for this crate has not been running for a looong time. We have not used Travis for years.

This PR:
* Removes the defunct Travis CI
* Adds github CI that checks for:
  * Rust formatting
  * Audit dependencies
  * Build and run tests
  * Builds with minimal dependencies
  * Git commit message style
* Checks in the lockfile for a more consistent CI experience

I wish we could also run `cargo clippy`. Hopefully we can in the future. But currently clippy complains about so much that I leave it as a separate exercise.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/89)

### CODE REVIEW

**Comment by pronebird** [comment]
Note that running tests on macOS require root, since we access `/usr/bin/pf`

**Comment by faern** [comment]
In this case the tests can't even be *built*. Look at the errors. My guess is that `pfvar.rs` must be re-generated with a newer version of bindgen or something.

**Comment by pronebird** [comment]
> In this case the tests can't even be _built_. Look at the errors. My guess is that `pfvar.rs` must be re-generated with a newer version of bindgen or something.

Yes either rebuild with new bindgen or pick it up from https://github.com/mullvad/pfctl-rs/pull/87 where I had also update pfvar.h with the most recent.

**Review by Serock3 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/89)* status: all files reviewed, 3 unresolved discussions (waiting on @faern)

___
*[`.github/workflows/build-and-test.yml` line 37 at r4](https://reviewable.io/reviews/mullvad/pfctl-rs/89#-Nz3V57L4rBygantPI7S:-Nz3V57L4rBygantPI7T:b4imji7) ([raw file](https://github.com/mullvad/pfctl-rs/blob/2ac914a415f7ef566d6a44e18d274b284c81a051/.github/workflows/build-and-test.yml#L37)):*
> ```YAML
>         # Since the tests modify global state (the system firewall) they cannot run in parallel.
>         # The integration tests must run as root since they write firewall state (/dev/pf)
>         run: sudo cargo test -- --test-threads=1
> ```

The output of the action seems to indicate that this command causes a rebuild, which will then be done with root access
___
*[`.github/workflows/cargo-audit.yml` line 35 at r4](https://reviewable.io/reviews/mullvad/pfctl-rs/89#-Nz3Y9WUDXhqNLfQAYzY:-Nz3Y9WUDXhqNLfQAYzZ:b-ionyko) ([raw file](https://github.com/mullvad/pfctl-rs/blob/2ac914a415f7ef566d6a44e18d274b284c81a051/.github/workflows/cargo-audit.yml#L35)):*
> ```YAML
>           # Ignored audit issues. This list should be kept short, and effort should be
>           # put into removing items from the list.
>           ignore:
> ```

The ignore section is empty, should it still be there?
___
*[`.github/workflows/formatting.yml` line 5 at r4](https://reviewable.io/reviews/mullvad/pfctl-rs/89#-Nz3YY-j5G0yJxSeD1tg:-Nz3YY-j5G0yJxSeD1th:b-9rj6ak) ([raw file](https://github.com/mullvad/pfctl-rs/blob/2ac914a415f7ef566d6a44e18d274b284c81a051/.github/workflows/formatting.yml#L5)):*
> ```YAML
> on:
>   pull_request:
>     paths:
> ```

Should `rustfmt.toml` not be included here?

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/89)* status: all files reviewed, 3 unresolved discussions (waiting on @Serock3)

___
*[`.github/workflows/cargo-audit.yml` line 35 at r4](https://reviewable.io/reviews/mullvad/pfctl-rs/89#-Nz3Y9WUDXhqNLfQAYzY:-Nz3cAH38FmE0f2lg8eM:b6g9cn2) ([raw file](https://github.com/mullvad/pfctl-rs/blob/2ac914a415f7ef566d6a44e18d274b284c81a051/.github/workflows/cargo-audit.yml#L35)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

The ignore section is empty, should it still be there?
</blockquote></details>

I thought it was better to keep it. Since it makes it easier to add when needed. Most projects will oscillate between zero and ~1-2 ignored issues. And if they every time they go from zero to non-zero have to add the boilerplate including the docs, that's more churn. I figured it's nicer to keep the docs and keyword even when empty. Do you agree?
___
*[`.github/workflows/formatting.yml` line 5 at r4](https://reviewable.io/reviews/mullvad/pfctl-rs/89#-Nz3YY-j5G0yJxSeD1tg:-Nz3c2CtCTF8ZZ6_YIVG:b-r1jhjm) ([raw file](https://github.com/mullvad/pfctl-rs/blob/2ac914a415f7ef566d6a44e18d274b284c81a051/.github/workflows/formatting.yml#L5)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

Should `rustfmt.toml` not be included here?
</blockquote></details>

I was hoping you would not see that one. Because I aim to remove that settings file but I wanted to keep it to a separate PR to not scope creep.

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/89)* status: all files reviewed, 3 unresolved discussions (waiting on @Serock3)

___
*[`.github/workflows/formatting.yml` line 5 at r4](https://reviewable.io/reviews/mullvad/pfctl-rs/89#-Nz3YY-j5G0yJxSeD1tg:-Nz3cgw619oPAXe7ZasM:bdnig1v) ([raw file](https://github.com/mullvad/pfctl-rs/blob/2ac914a415f7ef566d6a44e18d274b284c81a051/.github/workflows/formatting.yml#L5)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I was hoping you would not see that one. Because I aim to remove that settings file but I wanted to keep it to a separate PR to not scope creep.
</blockquote></details>

https://github.com/mullvad/pfctl-rs/pull/95

**Review by Serock3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/89)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`.github/workflows/cargo-audit.yml` line 35 at r4](https://reviewable.io/reviews/mullvad/pfctl-rs/89#-Nz3Y9WUDXhqNLfQAYzY:-Nz3cW5n2KuyVCgXFXrz:b-my31f8) ([raw file](https://github.com/mullvad/pfctl-rs/blob/2ac914a415f7ef566d6a44e18d274b284c81a051/.github/workflows/cargo-audit.yml#L35)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I thought it was better to keep it. Since it makes it easier to add when needed. Most projects will oscillate between zero and ~1-2 ignored issues. And if they every time they go from zero to non-zero have to add the boilerplate including the docs, that's more churn. I figured it's nicer to keep the docs and keyword even when empty. Do you agree?
</blockquote></details>

Alright
___
*[`.github/workflows/formatting.yml` line 5 at r4](https://reviewable.io/reviews/mullvad/pfctl-rs/89#-Nz3YY-j5G0yJxSeD1tg:-Nz3cbFrEjiK63CFJ8Kj:b-21qpmf) ([raw file](https://github.com/mullvad/pfctl-rs/blob/2ac914a415f7ef566d6a44e18d274b284c81a051/.github/workflows/formatting.yml#L5)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I was hoping you would not see that one. Because I aim to remove that settings file but I wanted to keep it to a separate PR to not scope creep.
</blockquote></details>

Haha I see, let's ignore it for now then.

**Review by Serock3 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/89)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
